In [1]:
import numpy as np

In [ ]:
first = np.arange(1 , 21)
first.resize(4 , 5)
print( "main\n", first)
print( "sum for each columns\n" , first.sum(axis=0))
print("mean for each rows\n" , first.mean(axis=1).astype(int))

first[first > 10] = 10
first



maskbool = first % 3 == 0


result = first[maskbool]

print("333333\n" , result) 


main
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
sum for each columns
 [34 38 42 46 50]
mean for each rows
 [ 3  8 13 18]
333333
 [3 6 9]


In [58]:
import numpy as np

first = np.arange(1, 21).reshape(4, 5)

# ماسک مضرب‌های 3 از خود آرایه‌ی دو بعدی
maskbool = first % 3 == 0

# اعمال ماسک
result = first[maskbool]

print(result)  # خروجی: [ 3  6  9 12 15 18]


[ 3  6  9 12 15 18]


In [62]:
import pandas as pd

In [67]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'city': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'salary': [70000, 80000, 65000, 90000]
}

df = pd.DataFrame(data)
df


name  age           city  salary
0    Alice   25       New York   70000
1      Bob   30  San Francisco   80000
2  Charlie   35    Los Angeles   65000
3    David   40        Chicago   90000

In [ ]:
df[['age' , 'salary']].mean()

age          32.5
salary    76250.0
dtype: float64

In [75]:
df[df['salary'] > 75000]

name  age           city  salary
1    Bob   30  San Francisco   80000
3  David   40        Chicago   90000

In [83]:
df['Tax'] = (df['salary'] * 0.1).astype(int)
df

name  age           city  salary   Tax
0    Alice   25       New York   70000  7000
1      Bob   30  San Francisco   80000  8000
2  Charlie   35    Los Angeles   65000  6500
3    David   40        Chicago   90000  9000

In [87]:
df.sort_values('age' , ascending=False)

name  age           city  salary   Tax
3    David   40        Chicago   90000  9000
2  Charlie   35    Los Angeles   65000  6500
1      Bob   30  San Francisco   80000  8000
0    Alice   25       New York   70000  7000