In [2]:
import numpy as np
import time

In [3]:
def python_version() :
  A

In [4]:
A =list(range(2 , 21))
i = 4
if i in A :
  i = i + 1
  print("yes")
  

yes


In [5]:
A = list(range(2 , 21))
i = 4
while i in A :
  print("yes")
  i -= 1

yes
yes
yes


In [6]:
j = 3 #Scalar
i = [1, 2, 3] #vector
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
] #marix
x = [
    [[1, 2, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]], #matrix
    [[5, 2, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]],#matrix
    [[1, 7, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]],#matrix
    [[1, 7, 3], [6, 2, 3 ], [8, 4, 2], [8, 4, 2]]#matrix

] #tensor

In [7]:
temp = np.array(x)
print(type(temp))

<class 'numpy.ndarray'>


In [8]:
testnarr = np.array([1 , 2 , 3 , 4  , 5])

In [9]:
np.resize(testnarr , (3 , 3))

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4]])

In [10]:
    X = np.arange(100000000)
    Y = np.arange(100000000)
    Z = X + Y
    print(Z)

[        0         2         4 ... 199999994 199999996 199999998]


In [11]:
np.sin(90)

np.float64(0.8939966636005579)

In [12]:
matrix = [[1 , 12] , [4 , 5]] 
matrix = np.array(matrix)
matrix.T

array([[ 1,  4],
       [12,  5]])

In [13]:
x = [ 'a' , 'b' , 'c' , 'd' , 'e' , 'f']
x[-1:-4:-1]


['f', 'e', 'd']

In [24]:
test = np.array([1, 2,3, 4 , 5 , 6 , 7])
print(type(test))

<class 'numpy.ndarray'>


In [33]:
test2 = test[2 : 6]
test2[0] = 12
print(test2)
test

[12  4  5  6]


array([ 1,  2, 12,  4,  5,  6,  7])

In [51]:
arr = np.array([10, 20, 30, 40])
v = arr[[0,1]]  # fancy indexing
v[0] = 999
print(arr)  # arr تغییر نکرد
v


[10 20 30 40]


array([999,  20])

In [47]:
boli = [False , False , True , True]
arr[boli] 

array([30, 40])

In [42]:
mask = arr > 20
print(mask)
v = arr[mask]  # boolean indexing → کپی است
v[0] = 777
print(arr)  # arr تغییر نکرد
v


[False False  True  True]
[10 20 30 40]


array([777,  40])

In [50]:
p = arr[0:2]
p[0] = 23
print(p)
arr

[23 20]


array([23, 20, 30, 40])

In [62]:
a = np.arange(10)
v = a.reshape((2, 5))  # view
v


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
a = np.array([[1, 2], [3, 4]])
a.ravel()

array([1, 2, 3, 4])

In [ ]:
a = np.arange(10)
s = a[::2]
s[0] = 222
print(s[0])
a

222


array([222,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [74]:
a = np.arange(12)
s = a[::2]
b = s.reshape(2  , 3)
b[0][0] = 222
print(b)
a

[[222   2   4]
 [  6   8  10]]


array([222,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [93]:
x = np.arange(10)
x.resize(3 , 1)
x


array([[0],
       [1],
       [2]])

In [104]:
a = np.arange(10).reshape(2 , 5)
b = np.random.randint(10 , 21 , (2 , 5))
print(a , b)
a * b

[[0 1 2 3 4]
 [5 6 7 8 9]] [[19 14 14 15 17]
 [11 17 18 19 15]]


array([[  0,  14,  28,  45,  68],
       [ 55, 102, 126, 152, 135]])

In [105]:
import pandas as pd

In [ ]:
data = pd.Series([1 , 2  , 3 , 4 , 5] , index= ['a' , 'b' , 'c' , 'd' , 'e'])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
import pandas as pd

animals = {
    'n1': 'Tiger',
    'n2': 'Bear',
    'n3': 'Moose'
}
p_animals = pd.Series(animals)

animals = {
    'n1': 'Tiger2',
    'n2': 'Bear2',
    'n3': 'Moose2'
}
p_animals2 = pd.Series(animals)

animals = {
    'n1': 'Tiger3',
    'n2': 'Bear3',
    'n3': 'Moose3'
}
p_animals3 = pd.Series(animals)

df = pd.DataFrame([p_animals, p_animals2, p_animals3], index=['r1', 'r2', 'r3'])
df

n1     n2      n3
r1   Tiger   Bear   Moose
r2  Tiger2  Bear2  Moose2
r3  Tiger3  Bear3  Moose3